version: '3'
services:
  web:
    container_name: django_project
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: >
#      sh -c "pip install psycopg2-binary &&
#             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/taskmgmt
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/task_mgmt

  db:
    container_name: postgres_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: task_mgmt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data: